### ISSUE TITLE
$^O is MSWin32 on Windows, not just Win32

### ISSUE THREAD

**Issue by nanis** [perlancar/perl-PERLANCAR-File-HomeDir#1]
On [line 19 in HomeDir.pm](https://github.com/perlancar/perl-PERLANCAR-File-HomeDir/blob/master/lib/PERLANCAR/File/HomeDir.pm#L19), you have 

```
 if ($^O eq 'Win32') {
```

but, on Windows, `$^O` is set to `'MSWin32'`, not just `'Win32'`. Therefore, the test fails, and causes the `else` block to be executed where you have:

```
 my @pw = getpwuid($>);
```

which of course croaks on Windows with:

`ERROR 500: Died: The getpwuid function is unimplemented at C:/opt/perl-5.20.2/site/lib/PERLANCAR/File/HomeDir.pm line 28.`

This then causes failures like:

<pre>t\run.t ................... 4/?
        #   Failed test 'output_re'
        #   at C:\Users\sinan\.cpanm\work\1428434154.3812\Perinci-CmdLine-Lite-1.05\blib\lib/Test/Perinci/CmdLine.pm line 70.
        #                   'ERROR 500: Died: The getpwuid function is unimplemented at C:/opt/perl-5.20.2/site/lib/PERLANCAR/File/HomeDir.pm line 28.
        # '
        #     doesn't match '(?^:^a=101\nb=201\nc=\nd=\ne=$)'
        # output is <ERROR 500: Died: The getpwuid function is unimplemented at C:/opt/perl-5.20.2/site/lib/PERLANCAR/File/HomeDir.pm line 28.
        # >
        # Looks like you failed 1 test of 2.

    #   Failed test 'test_run: --config-path'
    #   at C:\Users\sinan\.cpanm\work\1428434154.3812\Perinci-CmdLine-Lite-1.05\blib\lib/Test/Perinci/CmdLine.pm line 77.
    # Looks like you failed 1 test of 12.

#   Failed test 'config'</pre>

**Comment by perlancar** [comment]
Thanks, Sinan. Fixed & released.
